export const LocationsDetails = [
  {
    title: "Goa",
    href: "https://www.fabhotels.com/blog/wp-content/uploads/2015/10/shutterstock_177087344.jpg",
    cName: "location",
    duration: "4 Days",
    price: "₹ 20,000",
    summary: "Famous for its pristine beaches, hippie vibes, laidback lifestyle and vibrant parties, Goa is counted among the best holiday destinations in India. The union territory is frequented by tourists year-round, especially in the winter season when the climate is pleasant, and the entire place comes alive with Christmas and New Year celebrations. However, seasoned tourists do not shun Goa during summer either. If you are looking for a peaceful and economical holiday, try to visit Goa during the offseason when the sun-kissed beaches, flea markets and other attractions are less crowded.",
  },
  {
    title: "Agra",
    href: "https://www.fabhotels.com/blog/wp-content/uploads/2019/04/Agra1.jpg",
    cName: "location",
    duration: "2 Days",
    price: "₹ 10,000",
    summary: "Say Agra and the first thing that comes to mind is the magnificent Taj Mahal, one of the Seven Wonders of the World. This beautiful city with its rich historical background is situated in Uttar Pradesh, on the banks of River Yamuna. It is counted among the top tourist places in India for architecture lovers and history buffs, thanks to many amazing Mughal architectural masterpieces that adorn the cityscape. No matter how many times you visit Agra, the charm of the Taj Mahal and other monuments will never fail to impress. The city is a treat for shopaholics and foodies as well.",
  },
  {
    title: "Rajasthan",
    href: "https://www.fabhotels.com/blog/wp-content/uploads/2019/03/Amer-Fort.jpg",
    cName: "location",
    duration: "7 Days",
    price: "₹ 35,000",
    summary: "The land of kings, Rajasthan is a vibrant state that attracts history buffs, architecture lovers, wildlife enthusiasts and foodies alike. It lies in the north-western part of India and boasts an impressive amalgamation of natural beauty and manmade structures. From beautiful lakes, vast deserts and rich wildlife to magnificent palaces, forts and temples, the city has so many things for a wonderful vacation. What’s more, a road trip here takes you through several small and beautiful villages showcasing rich Rajasthani culture and traditions.",
  },
  {
    title: "Delhi",
    href: "https://www.fabhotels.com/blog/wp-content/uploads/2019/02/Red-Fort.jpg",
    cName: "location",
    duration: "3 Days",
    price: "₹ 15,000",
    summary: "New Delhi, the national capital of India, is one of the most cliched yet popular tourist destinations in the country. Delhi is dotted with iconic Mughal monuments, temples, heritage sites, performing arts venues, colourful bazaars, shopping malls, planetariums, museums, and restaurants, so there is something for everyone here. Chandni Chowk, the oldest and busiest market in the country, is in Delhi. The city also houses many places of political importance, like Rashtrapati Bhawan, Parliament of India, and India Gate.",
  },
  {
    title: "Munnar",
    href: "https://www.fabhotels.com/blog/wp-content/uploads/2019/09/Munnar-Kerala.jpg",
    cName: "location",
    duration: "4 Days",
    price: "₹ 20,000",
    summary: "Nestled in the Western Ghats in the state of Kerala, Munnar is counted among the most serene and beautiful places to visit in India. The hill station boasts impeccable natural beauty in the form of rolling hills, scenic valleys, virgin forests, waterfalls, streams, national parks, tea and spice plantations and winding walkways. The hill station was a popular holiday destination for the British and you can see many churches, English colonial bungalows and cottages and other structures here.",
  },
  {
    title: "Coorg",
    href: "https://www.fabhotels.com/blog/wp-content/uploads/2018/05/Coorg-2.jpg",
    cName: "location",
    duration: "3 Days",
    price: "₹ 15,000",
    summary: "Surrounded by majestic mountain ranges and boasting a lush green landscape, Coorg or Kodagu is yet another cliched holiday destination that is worth the hype. This hill station is in the state of Karnataka and a popular weekend getaway for nature lovers and solace seekers. From lush green hills and sparkling streams to quaint villages and vast expanses of coffee and spice plantations, the charm of Coorg is unmatchable. Since Coorg enjoys pleasant weather year-round, it is a popular destination for people in Bangalore who are looking to escape the city chaos.",
  },
  {
    title: "Manali",
    href: "https://www.fabhotels.com/blog/wp-content/uploads/2018/09/Manali.jpg",
    cName: "location",
    duration: "3 Days",
    price: "₹ 15,000",
    summary: "Situated in the Kullu Valley of Himachal Pradesh, Manali draws tourists with its natural beauty and tranquillity. The hill station is frequented by travellers from across the country, especially during the summer season when cities reel under the scorching heat. Snow-capped mountains, dense forests, riverine valleys and sparkling streams add to the beauty of the hill station and make it one of the most popular holiday destinations in India. Besides spending time in serenity and soaking in the beauty of the surroundings, you can engage in thrilling adventure activities here for a memorable vacation.",
  },
  {
    title: "Ooty",
    href: "https://www.fabhotels.com/blog/wp-content/uploads/2018/05/Ooty-1.jpg",
    cName: "location",
    duration: "2 Days",
    price: "₹ 10,000",
    summary: "Ooty is one of the most frequented holiday destinations for tourists from Tamil Nadu, Kerala and Karnataka. Given the fact that the southern part of India gets too hot during the summer season, a trip to Ooty offers the much-needed respite from the heat. This picturesque and serene hill station is also a popular honeymoon destination among couples. Ooty offers stunning views of the Nilgiri Hills and lush green landscapes dotted with alpine woods, clear lakes, emerald green tea estates and colourful blossoms.",
  },
  {
    title: "Lonavala and Khandala",
    href: "https://www.fabhotels.com/blog/wp-content/uploads/2018/09/Lonavala.jpg",
    cName: "location",
    duration: "3 Days",
    price: "₹ 15,000",
    summary: "Perched at a height of 622 metres above sea level, Lonavala and Khandala are twin hill stations in the state of Maharashtra. Thanks to their pleasant weather conditions and proximity to Mumbai and Pune, the hill stations are frequented by Mumbaikars and Punekars year-round. Both Lonavala and Khandala come to life during the monsoon season when lush greenery, sparkling lakes and milky-white waterfalls add to the beauty of the landscape.",
  },
  {
    title: "Shillong",
    href: "https://www.fabhotels.com/blog/wp-content/uploads/2018/09/shillong.jpg",
    cName: "location",
    duration: "5 Days",
    price: "₹ 25,000",
    summary: "Known for pleasant weather conditions and picturesque locations, Shillong in Meghalaya is one of the most cliched yet highly frequented tourist destinations in India. The hill station is popularly known as Scotland of the East, thanks to the rolling hills, gushing waterfalls and lovely landscape that reminded European colonists of stunning Scotland. Shillong also boasts crystal-clear lakes, high mountain peaks and amazing golf courses, museums and cafes. What’s more, the distinct culture, delectable local cuisines and amazing shopping hubs promise a fun-filled vacation every time.",
  },
  {
    title: "Varanasi",
    href: "https://www.fabhotels.com/blog/wp-content/uploads/2019/04/Varanasi1.jpg",
    cName: "location",
    duration: "3 Days",
    price: "₹ 15,000",
    summary: "Situated on the banks of River Ganga in Uttar Pradesh, the holy city of Varanasi or Banaras is counted among the most sacred places in India. The city is known for some of the most revered temples and Ghats in the country and is frequented by devotees and tourists from across the world. Varanasi, one of the oldest cities in the world, is also popular as the home of Lord Shiva and Goddess Parvati. It is believed that taking a dip in the Ganges can wash away all your sins. The bustling city is popular for its museums, authentic Banarasi food, Banarasi sarees and handicrafts as well.",
  },
  {
    title: "Kolkata",
    href: "https://www.fabhotels.com/blog/wp-content/uploads/2019/12/2-days-trip-to-kolkata-600.jpg",
    cName: "location",
    duration: "4 Days",
    price: "₹ 20,000",
    summary: "Known as the City of Joy and rightly so, Kolkata is another holiday destination that is frequented by tourists from across the country. A beautiful blend of art, culture, fashion and literature, Kolkata is the perfect getaway for different types of travellers. What’s more, it is a delight for foodies, shopaholics and nightlife lovers as well. This vibrant city is a perfect example of old-world charm meeting modernisation. From historical monuments, temples and trams to modern science museums, gigantic shopping malls and fine dining restaurants, Kolkata has everything for a wonderful vacation.",
  },
  {
    title: "Amritsar",
    href: "https://www.fabhotels.com/blog/wp-content/uploads/2018/10/Amritsar.jpg",
    cName: "location",
    duration: "4 Days",
    price: "₹ 20,000",
    summary: "Steeped in history and spirituality, Amritsar is one of the most-visited cities in the state of Punjab. It is home to the famous Golden Temple or Sri Harmandir Sahib and is frequented by devout Sikhs and tourists from across the globe. The city also gives a nudge to your patriotic side with sites like Jallianwala Bagh and Wagah Border. The charm of Amritsar is such that tourists visit the place time and again to pay their respects at Golden Temple and watch the mesmerising Wagah-Attari Border ceremony held at the India-Pakistan border. ",
  },
  {
    title: "Sikkim",
    href: "https://www.fabhotels.com/blog/wp-content/uploads/2021/02/7.-Yumthang-Valley-in-Sikkim-copy.jpg",
    cName: "location",
    duration: "5 Days",
    price: "₹ 25,000",
    summary: "A jewel in the north-eastern part of India, Sikkim is one of the most beautiful and serene holiday destinations you will ever find. Although a vacation in Sikkim sounds cliched, the hill station is a popular choice among nature enthusiasts and peace seekers. From snow-capped mountains and colourful meadows to thick woodlands and exotic flowers, there are so many things that add a distinctive charm to this hill station. And that’s not all, the town also houses some pretty monasteries, stupas and Hindu shrines that make it a religiously significant place for the Hindus and Buddhists.",
  },
  {
    title: "Shimla",
    href: "https://www.fabhotels.com/blog/wp-content/uploads/2019/01/Shimla.jpg",
    cName: "location",
    duration: "4 Days",
    price: "₹ 20,000",
    summary: "Located in Himachal Pradesh at a height of 2276 metres above sea level, Shimla has been attracting honeymooners and families for decades. This hill station was the summer capital of British India, and so, the stunning colonial architecture and old-world charm here are unmissable. It is also home to a UNESCO World Heritage Site – Kalka-Shimla train route, which offers dramatic views of the surrounding hills and villages. You can also enjoy adventurous activities and relish local delicacies in the cosy restaurants, cafes and hotels in Shimla.",
  },
];
